version: "3"
services:
    web:
        container_name: riftapi
        build: ./api
        ports:
            - 5000:4005
    #     depends_on:
    #         - db
    # db:
    #     container_name: riftsql
    #     image: "microsoft/mssql-server-linux"
    #     ports:
    #         - 1401:1433
    #     environment:
    #         SA_PASSWORD: "Password!"
    #         ACCEPT_EULA: "Y"