version: "3"
services:
    web:
        build: ./api
        ports:
            - "4500:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux"
        environment:
            SA_PASSWORD: "your_password"
            ACCEPT_EULA: "Y"