export const SAVE_URL_SUCCESS = "SAVE_URL_SUCCESS";
export const SAVE_URL_FAILURE = "SAVE_URL_FAILURE";
export const RECEIVE_ARTICLE_LIST = "RECEIVE_ARTICLE_LIST";
export const PUSH_TO_RIFT = "PUSH_TO_RIFT";